---
- name: Copy task_4_motd.txt to /etc/motd
  become: true
  copy:
    src: task_4_motd.txt
    dest: /etc/motd
    owner: devops
    group: devops
    mode: u+rw,g-wx,o-rwx
    
- name: Configure /etc/issue.net
  become: true
  template:
    src: motd.j2
    dest: /etc/issue.net
    owner: devops
    group: devops
    mode: 0644