---
- name: Create a volume group and resize the volume group to the maximum possible
  become: true
  community.general.lvg:
    vg: "{{ storage_vars.vg_name }}"
    pvs: "{{ storage_vars.device }}"
    pvresize: true

- name: Create a logical volume the size of all remaining space in the volume group
  become: true
  community.general.lvol:
    vg: "{{ storage_vars.vg_name }}"
    lv: "{{ storage_vars.lvm_name }}"
    size: 100%FREE

- name: Reformat device
  become: true
  command: mkfs -t xfs -f /dev/{{ storage_vars.vg_name }}/{{ storage_vars.lvm_name }}

- name: Apply vgchanges
  become: true
  command: vgchange -ay

- name: Mount device to directory
  become: true
  command: mount /dev/{{ storage_vars.vg_name }}/{{ storage_vars.lvm_name }} {{ storage_vars.directory }}

- name: Dispaly uuid & store in variable
  become: true
  command: blkid -s UUID -o value /dev/{{ storage_vars.vg_name }}/{{ storage_vars.lvm_name }}
  register: uuid_swap

- name: Add the below lines
  become: true
  blockinfile:
    path: /etc/fstab
    state: present
    block: |
      UUID={{ uuid_swap.stdout }}  /var/www/html xfs defaults 0 0 
