---
- name: Get packages
  become: true
  command: dnf list updates
  register: updatables

- name: List packages
  ansible.builtin.debug:
    msg: "{{ updatables.stdout }}"

- name: Update packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true